mygame: main.o printEvenNumbersArray.o
	gcc -Wall main.o printEvenNumbersArray.o -o exercicio1

main.o: main.c
	gcc -Wall -c main.c -o main.o

printStuff.o: printStuff.c
	gcc -Wall -c printEvenNumbersArray.c -o printEvenNumbersArray.o	

run: exercicio1
	./exercicio1

