mygame: main.o printStuff.o
	gcc -Wall main.o printStuff.o -o exercicio1

main.o: main.c
	gcc -Wall -c main.c -o main.o

printStuff.o: printStuff.c
	gcc -Wall -c printStuff.c -o printStuff.o	

run: exercicio1
	./exercicio1

